# Generated by Django 4.1.1 on 2023-01-07 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtube', '0019_delete_channel_alter_video_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailUpdateSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('videos', models.ManyToManyField(to='youtube.video')),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tex_text', models.TextField(null=True)),
                ('youtube_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
