# Generated by Django 4.1.1 on 2023-01-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0024_remove_channelsection_data_remove_playlist_data_and_more'),
        ('thumbnail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailcontent',
            name='youtube_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube.video'),
        ),
    ]
