# Generated by Django 4.1.1 on 2023-01-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0024_remove_channelsection_data_remove_playlist_data_and_more'),
        ('thumbnail', '0002_alter_thumbnailcontent_youtube_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tex_text', models.TextField(null=True)),
                ('youtube_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.video')),
            ],
        ),
    ]
