version: "3.7"

services:
  ugosite-data:
    image: mysql:latest
    volumes: 
      - ugosite-bd:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ugosites
      TZ: 'Asia/Tokyo'

  web:
    image: ugosite
    ports:
      - "8000:8002"
    working_dir: /ugosite
    volumes:
      - ./:/ugosite
    environment:
      MYSQL_HOST: ugosite-data
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: ugosites
    depends_on:
      - ugosite-data

volumes:
  ugosite-bd:
    external: true