# Generated by Django 4.1.1 on 2023-02-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printviewer', '0002_folder_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent',
            new_name='parent_folder',
        ),
        migrations.RenameField(
            model_name='print',
            old_name='folder',
            new_name='parent_folder',
        ),
    ]
