# Generated by Django 4.1.1 on 2023-02-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printviewer', '0003_rename_parent_folder_parent_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='no_name_folder', max_length=200),
        ),
    ]
