# Generated by Django 4.1.1 on 2023-01-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtube', '0021_remove_searchedvideoset_search_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(blank=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.videoonapp')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='VideoSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('video_genres', models.ManyToManyField(to='youtube.videogenre')),
                ('video_types', models.ManyToManyField(to='youtube.videotype')),
            ],
        ),
        migrations.CreateModel(
            name='SearchedVideoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_search.videosearch')),
                ('searched_videos', models.ManyToManyField(to='video_search.searchedvideo')),
            ],
        ),
    ]
