# Generated by Django 4.1.1 on 2023-01-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0025_video_point_video_problem_video_source_and_more'),
        ('video_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video'),
        ),
    ]
