# Generated by Django 4.1.1 on 2023-03-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_playlistitemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsectionid',
            name='raw_text',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='playlistitemid',
            name='raw_text',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
