# Generated by Django 4.1.1 on 2022-12-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_thumbnail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoOnApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='タイトルなし', max_length=200)),
                ('source', models.CharField(default='オリジナル', max_length=200)),
                ('type', models.CharField(choices=[('計算', '計算問題'), ('基本', '基本事項'), ('典型', '典型問題'), ('応用', '応用問題'), ('強化', '強化問題'), ('他', 'その他')], default='他', max_length=200)),
                ('genre', models.CharField(default='他', max_length=200)),
                ('table', models.CharField(default='00:00 目次なし', max_length=1000)),
                ('problem', models.TextField(default='問題なし', max_length=10000)),
                ('point', models.TextField(default='要点なし', max_length=10000)),
                ('youtube_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youtube.video')),
            ],
        ),
    ]
