# Generated by Django 4.1.1 on 2023-03-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_alter_channelsectionid_raw_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitemid',
            name='raw_text',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
