# Generated by Django 4.1.1 on 2022-12-27 12:17

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_alter_videoonapp_genre_alter_videoonapp_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoonapp',
            name='table',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=2100, null=True, size=20),
        ),
    ]
