# Generated by Django 4.1.1 on 2022-12-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_videoonapp_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoonapp',
            old_name='table',
            new_name='table_list',
        ),
    ]
