# Generated by Django 4.1.1 on 2023-03-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_remove_playlistitemid_raw_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitemid',
            name='raw_text_100',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
