# Generated by Django 4.1.1 on 2023-01-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_videoonapp_videoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searched_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.ManyToManyField(to='youtube.video')),
            ],
        ),
    ]
