# Generated by Django 4.1.1 on 2023-01-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_searched_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('計算', '計算問題'), ('基本', '基本事項'), ('典型', '典型問題'), ('応用', '応用問題'), ('強化', '強化問題'), ('他', 'その他')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Searched_Videos',
        ),
        migrations.AddField(
            model_name='videosearch',
            name='video_type',
            field=models.ManyToManyField(to='youtube.videotype'),
        ),
        migrations.AddField(
            model_name='videosearch',
            name='videos',
            field=models.ManyToManyField(to='youtube.videoonapp'),
        ),
    ]
