# Generated by Django 4.1.1 on 2023-01-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_videosearch_videotype_delete_searched_videos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosearch',
            old_name='video_type',
            new_name='video_types',
        ),
    ]
