# Generated by Django 4.1.1 on 2023-01-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_rename_video_type_videosearch_video_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotype',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
