# Generated by Django 4.1.1 on 2023-01-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_alter_videotype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(blank=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.videoonapp')),
            ],
            options={
                'ordering': ['num'],
            },
        ),
        migrations.RemoveField(
            model_name='videosearch',
            name='videos',
        ),
        migrations.CreateModel(
            name='SearchedVideoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youtube.videosearch')),
                ('searched_videos', models.ManyToManyField(to='youtube.searchedvideo')),
            ],
        ),
    ]
