# Generated by Django 4.1.1 on 2023-01-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_searchedvideo_remove_videosearch_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedvideoset',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.videosearch'),
        ),
    ]
