# Generated by Django 4.1.1 on 2023-01-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0013_alter_searchedvideoset_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
