# Generated by Django 4.1.1 on 2023-01-02 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0014_videogenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoonapp',
            name='video_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.videotype'),
        ),
    ]
