# Generated by Django 4.1.1 on 2023-01-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_videoonapp_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosearch',
            name='video_genres',
            field=models.ManyToManyField(to='youtube.videogenre'),
        ),
    ]
