# Generated by Django 4.1.1 on 2023-01-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0016_videosearch_video_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoonapp',
            name='video_genre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.videogenre'),
        ),
    ]
