# Generated by Django 4.1.1 on 2023-01-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0017_videoonapp_video_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoonapp',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='videoonapp',
            name='type',
        ),
    ]
