# Generated by Django 4.1.1 on 2023-01-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0018_remove_videoonapp_genre_remove_videoonapp_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='videoonapp',
            options={'ordering': ['id']},
        ),
    ]
