# Generated by Django 4.1.1 on 2023-01-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0019_delete_channel_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupdateset',
            name='videos',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
        migrations.DeleteModel(
            name='VideoUpdateSet',
        ),
    ]
