# Generated by Django 4.1.1 on 2023-01-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0020_remove_videoupdateset_videos_delete_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedvideoset',
            name='search',
        ),
        migrations.RemoveField(
            model_name='searchedvideoset',
            name='searched_videos',
        ),
        migrations.RemoveField(
            model_name='videosearch',
            name='video_genres',
        ),
        migrations.RemoveField(
            model_name='videosearch',
            name='video_types',
        ),
        migrations.DeleteModel(
            name='SearchedVideo',
        ),
        migrations.DeleteModel(
            name='SearchedVideoSet',
        ),
        migrations.DeleteModel(
            name='VideoSearch',
        ),
    ]
