# Generated by Django 4.1.1 on 2023-01-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0021_remove_searchedvideoset_search_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VideoId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=20)),
            ],
        ),
    ]
