# Generated by Django 4.1.1 on 2023-01-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0022_channelid_playlistid_videoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
