# Generated by Django 4.1.1 on 2023-01-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0023_channelsectionresponse_playlistitemresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelsection',
            name='data',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='data',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='data',
        ),
        migrations.AddField(
            model_name='channelsection',
            name='playlists',
            field=models.ManyToManyField(to='youtube.playlist'),
        ),
        migrations.AddField(
            model_name='channelsection',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlistId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube.playlistid'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube.playlist'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='position',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube.video'),
        ),
    ]
