# Generated by Django 4.1.1 on 2023-01-14 07:21

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0024_remove_channelsection_data_remove_playlist_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='point',
            field=models.TextField(default=None, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='problem',
            field=models.TextField(default=None, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='table_list',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=2100, null=True, size=20),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='videoId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube.videoid'),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='new_json_data',
            field=models.JSONField(blank=True, help_text='補正後のデータです。', null=True),
        ),
    ]
