# Generated by Django 4.1.1 on 2023-01-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_search', '0002_alter_searchedvideo_video'),
        ('youtube', '0025_video_point_video_problem_video_source_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoOnApp',
        ),
    ]
