# Generated by Django 4.1.1 on 2023-01-15 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0026_delete_videoonapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelid',
            name='channelId',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlistId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube.playlistid', unique=True),
        ),
        migrations.AlterField(
            model_name='playlistid',
            name='playlistId',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube.videoid', unique=True),
        ),
        migrations.AlterField(
            model_name='videogenre',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='videoid',
            name='videoId',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='videotype',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
