# Generated by Django 4.1.1 on 2023-01-15 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0027_alter_channelid_channelid_alter_playlist_playlistid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlistId',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube.playlistid'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoId',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube.videoid'),
        ),
    ]
