# Generated by Django 4.1.1 on 2023-01-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0028_alter_playlist_playlistid_alter_video_videoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelid',
            old_name='channelId',
            new_name='raw_text',
        ),
        migrations.RenameField(
            model_name='playlistid',
            old_name='playlistId',
            new_name='raw_text',
        ),
        migrations.RenameField(
            model_name='videoid',
            old_name='videoId',
            new_name='raw_text',
        ),
    ]
