# Generated by Django 4.1.1 on 2023-01-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0029_rename_channelid_channelid_raw_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='data',
        ),
        migrations.RemoveField(
            model_name='video',
            name='new_data',
        ),
    ]
