# Generated by Django 4.1.1 on 2023-01-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0030_remove_video_data_remove_video_new_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSectionId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
