# Generated by Django 4.1.1 on 2023-01-17 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0031_channelsectionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsection',
            name='channelSectionId',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='youtube.channelsectionid'),
        ),
    ]
