# Generated by Django 4.1.1 on 2023-01-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0032_channelsection_channelsectionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='video_gerne',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.videogenre'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='video_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.videotype'),
        ),
    ]
