# Generated by Django 4.1.1 on 2023-01-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0033_playlist_video_gerne_playlist_video_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='video_gerne',
            new_name='video_genre',
        ),
    ]
