# Generated by Django 4.1.1 on 2023-01-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0034_rename_video_gerne_playlist_video_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_genre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.videogenre'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.videotype'),
        ),
    ]
