# Generated by Django 4.1.1 on 2023-01-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0035_video_video_genre_video_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(default='', max_length=50),
        ),
    ]
