# Generated by Django 4.1.1 on 2023-01-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0037_university_source_video_source_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='name',
        ),
        migrations.AddField(
            model_name='source',
            name='division',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
