# Generated by Django 4.1.1 on 2023-01-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0038_remove_source_name_source_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(default='', max_length=50, null=True),
        ),
    ]
