# Generated by Django 4.1.1 on 2023-01-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0039_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='division',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='year',
            field=models.DateField(default=None, null=True),
        ),
    ]
