# Generated by Django 4.1.1 on 2023-01-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0040_alter_source_division_alter_source_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='division',
            new_name='setting_division',
        ),
        migrations.RemoveField(
            model_name='source',
            name='year',
        ),
        migrations.AddField(
            model_name='source',
            name='setting_year',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
