# Generated by Django 4.1.1 on 2023-01-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0041_rename_division_source_setting_division_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='setting_division',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='setting_year',
            new_name='year',
        ),
    ]
