# Generated by Django 4.1.1 on 2023-01-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0042_rename_setting_division_source_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='question_num',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
