# Generated by Django 4.1.1 on 2023-02-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0021_alter_term_options_remove_term_description_and_more'),
        ('youtube', '0043_source_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='terms',
            field=models.ManyToManyField(to='ugosite.term'),
        ),
    ]
