# Generated by Django 4.1.1 on 2023-02-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0044_video_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='source',
        ),
    ]
