# Generated by Django 4.1.1 on 2023-02-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0045_remove_video_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='source_detail',
            new_name='source',
        ),
    ]
