# Generated by Django 4.1.1 on 2023-02-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0046_rename_source_detail_video_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['-id']},
        ),
    ]
