# Generated by Django 4.1.1 on 2023-02-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0022_alter_term_options'),
        ('youtube', '0049_remove_videogenre_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenre',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugosite.category'),
        ),
    ]
