# Generated by Django 4.1.1 on 2023-02-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0053_alter_channelid_raw_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelid',
            name='raw_text',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='channelsectionid',
            name='raw_text',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='playlistid',
            name='raw_text',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='videoid',
            name='raw_text',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
