# Generated by Django 4.1.1 on 2023-02-23 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('path', models.CharField(blank=True, default='/', max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('content', models.TextField(blank=True, help_text='記事の内容をHTML形式で入力してください', max_length=2000)),
                ('type', models.CharField(choices=[('BAS', '基本'), ('STU', '研究'), ('DEV', '発展'), ('SUP', '補足'), ('PRA', '演習'), ('TER', 'テーマ'), ('CAT', 'カテゴリ'), ('NOT', 'ノート'), ('OTH', 'その他')], default='OTH', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('type', models.CharField(choices=[('SUB', '科目'), ('CHA', '章'), ('SEC', '節'), ('SSE', '分節'), ('TER', 'テーマ'), ('OTH', 'その他')], default='OTH', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='このカテゴリのアイコンSVG', max_length=10000)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ugosite.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='記事のタイトルを入力してください', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('description', models.TextField(blank=True, max_length=10000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('answer', models.TextField(blank=True, max_length=10000, null=True, verbose_name='example_answer')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('parent_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ugosite.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用語名を入力してください', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('parent_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ugosite.section')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ugosite.category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='問題セットのタイトルを入力してください', max_length=200)),
                ('problems', models.ManyToManyField(to='ugosite.question')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('answer', models.TextField(blank=True, max_length=10000, null=True, verbose_name='example_answer')),
                ('link', models.URLField(blank=True, max_length=50, null=True)),
                ('articles', models.ManyToManyField(to='ugosite.article')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ugosite.subject'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ugosite.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ugosite.section'),
        ),
    ]
