# Generated by Django 4.1.1 on 2023-02-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCategory',
        ),
        migrations.RemoveField(
            model_name='article',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
