# Generated by Django 4.1.1 on 2022-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedyoutubeplaylist',
            name='youtubeplaylist_ptr',
        ),
        migrations.RemoveField(
            model_name='downloadedyoutubeplaylistitem',
            name='youtubeplaylistitem_ptr',
        ),
        migrations.RemoveField(
            model_name='downloadedyoutubevideo',
            name='youtubevideo_ptr',
        ),
        migrations.RemoveField(
            model_name='newcreatedyoutubeplaylist',
            name='youtubeplaylist_ptr',
        ),
        migrations.DeleteModel(
            name='TagForYoutube',
        ),
        migrations.RemoveField(
            model_name='updatedyoutubeplaylist',
            name='downloadedPlaylist',
        ),
        migrations.RemoveField(
            model_name='updatedyoutubeplaylist',
            name='youtubeplaylist_ptr',
        ),
        migrations.RemoveField(
            model_name='updatedyoutubevideo',
            name='downloadedVideo',
        ),
        migrations.RemoveField(
            model_name='updatedyoutubevideo',
            name='youtubevideo_ptr',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='caption',
            field=models.JSONField(blank=True, help_text='このFieldはYoutubeAPIによって読み込まれます。', null=True),
        ),
        migrations.DeleteModel(
            name='DownloadedYoutubePlaylist',
        ),
        migrations.DeleteModel(
            name='DownloadedYoutubePlaylistItem',
        ),
        migrations.DeleteModel(
            name='DownloadedYoutubeVideo',
        ),
        migrations.DeleteModel(
            name='NewCreatedYoutubePlaylist',
        ),
        migrations.DeleteModel(
            name='UpdatedYoutubePlaylist',
        ),
        migrations.DeleteModel(
            name='UpdatedYoutubeVideo',
        ),
    ]
