# Generated by Django 4.1.1 on 2022-11-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0002_remove_downloadedyoutubeplaylist_youtubeplaylist_ptr_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='TagForYoutube',
        # ),
    ]
