# Generated by Django 4.1.1 on 2022-11-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0003_delete_tagforyoutube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hue', models.IntegerField()),
                ('saturation', models.IntegerField()),
                ('lightness', models.IntegerField()),
            ],
        ),
    ]
