# Generated by Django 4.1.1 on 2023-02-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0003_rename_parent_subject_chapter_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFile',
        ),
    ]
