# Generated by Django 4.1.1 on 2023-02-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printviewer', '0001_initial'),
        ('ugosite', '0004_delete_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='prints',
            field=models.ManyToManyField(to='printviewer.print'),
        ),
    ]
