# Generated by Django 4.1.1 on 2022-11-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0006_youtubevideo_new_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayedVideo',
            fields=[
                ('youtubevideo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ugosite.youtubevideo')),
            ],
            bases=('ugosite.youtubevideo',),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='caption',
        ),
    ]
