# Generated by Django 4.1.1 on 2022-11-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0007_displayedvideo_delete_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisplayedVideo',
            new_name='RandomVideo',
        ),
    ]
