# Generated by Django 4.1.1 on 2022-11-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0008_rename_displayedvideo_randomvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
