# Generated by Django 4.1.1 on 2022-11-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0009_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannelSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='このFieldはYoutubeAPIによって読み込まれます。')),
            ],
        ),
    ]
