# Generated by Django 4.1.1 on 2022-12-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0010_youtubechannelsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='問題名を入力してください', max_length=200)),
                ('text', models.TextField(help_text='この問題の内容をJax形式で入力してください', max_length=1000)),
                ('answer', models.TextField(blank=True, help_text='この問題の解答例をTeX形式で入力してください', max_length=10000, null=True, verbose_name='example_answer')),
                ('articles', models.ManyToManyField(blank=True, help_text='この問題が含まれる記事を選んでください', null=True, to='ugosite.article')),
                ('source', models.ForeignKey(help_text='この問題のソースを選んでください', null=True, on_delete=django.db.models.deletion.CASCADE, to='ugosite.source')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='問題セットのタイトルを入力してください', max_length=200)),
                ('problems', models.ManyToManyField(to='ugosite.question')),
            ],
        ),
        migrations.CreateModel(
            name='VideoOnApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ugosite.youtubevideo')),
            ],
        ),
        migrations.AlterField(
            model_name='problem',
            name='articles',
            field=models.ManyToManyField(blank=True, help_text='この問題が含まれる記事を選んでください', null=True, to='ugosite.article'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.TextField(help_text='この問題の内容をJax形式で入力してください', max_length=1000),
        ),
        migrations.DeleteModel(
            name='RandomVideo',
        ),
    ]
