# Generated by Django 4.1.1 on 2022-12-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0011_question_questionset_videoonapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='articles',
        ),
        migrations.AlterField(
            model_name='problem',
            name='articles',
            field=models.ManyToManyField(help_text='この問題が含まれる記事を選んでください', to='ugosite.article'),
        ),
        migrations.CreateModel(
            name='YoutubeSambnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ugosite.youtubevideo')),
            ],
        ),
    ]
