# Generated by Django 4.1.1 on 2022-12-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0013_youtubevideoupdateset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YoutubeSambnail',
            new_name='YoutubeThumbnail',
        ),
        migrations.AddField(
            model_name='youtubevideoupdateset',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
