# Generated by Django 4.1.1 on 2022-12-15 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0015_youtubethumbnail_tex_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubethumbnail',
            name='youtube_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugosite.youtubevideo'),
        ),
    ]
