# Generated by Django 4.1.1 on 2022-12-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0016_alter_youtubethumbnail_youtube_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update_to_source',
            name='category_ptr',
        ),
        migrations.DeleteModel(
            name='Update_From_Source',
        ),
        migrations.DeleteModel(
            name='Update_To_Source',
        ),
    ]
