# Generated by Django 4.1.1 on 2022-12-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0019_videoonapp_genre_videoonapp_keywords_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoOnApp',
        ),
    ]
