# Generated by Django 4.1.1 on 2023-02-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0020_delete_videoonapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={},
        ),
        migrations.RemoveField(
            model_name='term',
            name='description',
        ),
        migrations.RemoveField(
            model_name='term',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='term',
            name='hurigana',
        ),
        migrations.RemoveField(
            model_name='term',
            name='related_terms',
        ),
    ]
