# Generated by Django 4.1.1 on 2023-02-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0021_alter_term_options_remove_term_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['name']},
        ),
    ]
