# Generated by Django 4.1.1 on 2023-02-17 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugosite', '0022_alter_term_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='data',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='playlistId',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='update_date',
        ),
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='このカテゴリの作成日を指定してください'),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='name', help_text='記事のタイトルを入力してください', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='このカテゴリの更新日を指定してください'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='name', help_text='記事のタイトルを入力してください', max_length=200),
        ),
    ]
